### ISSUE TITLE
Not generating payloads

### ISSUE THREAD

**Issue by fenceposterror** [mseclab/Burp-PyJFuzz#3]
The situation is as follows:
-  PJF version 1.1.2
- `pjf -t CHPTRSX -l 6 -p page --auto` generates test cases
- Burp Pro 1.7.30
- Extension loads without issue

Now, if I "Set Configuration", send my request to the Intruder, chose the extension to generate payloads and start the attack, the payload is always empty. Any idea what the issue could be? What other information do you need?

**Comment by dzonerzy** [comment]
Hi,
Is your pjf binary in PATH environment variable?
Anyway a screenshot of the configuration on burpsuite will help me handle your issue.

Regards,
Daniele

**Comment by R3zk0n** [comment]
Hi, I am having the same issue as a above. I have provided two screenshots below.
![alt text](https://i.imgur.com/eZqrgZR.png "Image 1")
![alt text](https://i.imgur.com/ozFW8lJ.png "Image 2")
![alt text](https://i.imgur.com/hMoniE8.png "Image 3")

If you need more information, please let me know 👍

**Comment by dzonerzy** [comment]
Please can you provide more information about the payload you're trying to fuzz, and an Intruder screenshot?

**Comment by fenceposterror** [comment]
![pjfuzz](https://user-images.githubusercontent.com/24934956/36105110-1df13eb8-1014-11e8-9ba1-2cd462969e96.png)

pjf is in PATH. The rest looks like R3zk0n.

**Comment by dzonerzy** [comment]
The issue here's pretty simple , you're trying to fuzz a single field inside the JSON while PyJFuzz expect a full JSON ,  anyway you're able to fuzz just the 'generateId' field by properly configuring the plugin.

Please read here to understand how to properly configure PyJFuzz https://dzonerzy.net/post/pyjfuzz-to-the-next-level

Regards,
Daniele

**Comment by fenceposterror** [comment]
Thanks!
